### PR TITLE
Python 3/2 code base

### PR DESCRIPTION
**Pull request by ocefpaf**
@kwilcox same as https://github.com/axiom-data-science/paegan/pull/1. Let me know if this is OK.

### CODE REVIEW

**Comment by ocefpaf** [comment]
There is no CI and I did not run the tests :scream:

**Comment by kwilcox** [comment]
Hehe, the tests are a bit much for a CI, I'll test next week and fix what needs fixing.

**Comment by ocefpaf** [comment]
Why we do not have a emoji for radar!!!

PS:  Note that some of our IOOS Python3 packages are broken right now.

**Comment by ocefpaf** [comment]
Thanks @kwilcox!

**Comment by kwilcox** [comment]
I will bump a new py3 compatible version soon

**Comment by ocefpaf** [comment]
Hehe. I was modifying the conda recipe to get it from master.  Now I will just wait.

**Pull request merged**
